 > ## About This Project

> We all know almost all competitive companies in the world right now, have business models
that make them the most profit as possible. To cut costs and increase profit margins
companies don’t invest resources on things like safety, environmental impacts etc. The
negligence for environmental impact research of company’s products can lead to
Environment destruction and Environmental degradation.

#### Importing all the libraries

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from tensorflow.keras.layers import Dense

#### Functions

In [6]:
def import_data():

    df = pd.read_csv("Dataset.csv",header=None)
    names = ["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics","Impact"]
    df.columns = names
    
    return df

#### Encoding The Labels Through Label Encoding

In [7]:
def label_encode(df):
    df_labelled = df.copy()

    label_encode = {"Impact": {"High":0, "Moderate":1, "Low":2}}

    df_labelled.replace(label_encode,inplace=True)
    return df_labelled

#### Adding The Functions

#### Standardizing the data

In [8]:
df = import_data()
df = label_encode(df)

x_values = df[["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics","Impact"]]
print(x_values.head())

standardise = StandardScaler()
x_values = standardise.fit_transform(x_values)
x_values_df = pd.DataFrame(x_values)

   Metals  Plastics  Electronics  Hazardous Liquids and Substances  Ceramics  \
0     100         0            0                                 0         0   
1      99         0            0                                 0         0   
2      98         0            0                                 0         0   
3      97         0            0                                 0         0   
4      96         0            0                                 0         0   

   Impact  
0       0  
1       0  
2       0  
3       0  
4       0  


the rting The Libraries 'Keras' And 'Tensorfolwlow'

#### Model

In [9]:
from keras.models import Sequential
from tensorflow.keras.layers import Dense

In [10]:
model = Sequential()

model.add(Dense(6,input_dim=6,activation='relu'))
model.add(Dense(6,activation='relu')) 
model.add(Dense(3,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 42        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 3)                 21        
                                                                 
Total params: 105
Trainable params: 105
Non-trainable params: 0
_________________________________________________________________


In [12]:
from tensorflow.keras.utils import to_categorical

label_encode = {"Impact": {"High":0, "Moderate":1, "Low":2}}

df.replace(label_encode,inplace=True)

y_values = df['Impact']

y_values = to_categorical(y_values)


In [13]:
model.fit(x_values,y_values,epochs=100,shuffle=True, batch_size=1)

Epoch 1/100
654/654 [==============================] - 2s 3ms/step - loss: 0.7848 - accuracy: 0.6896
Epoch 2/100
654/654 [==============================] - 1s 2ms/step - loss: 0.3889 - accuracy: 0.8700
Epoch 3/100
654/654 [==============================] - 1s 2ms/step - loss: 0.1427 - accuracy: 0.9862
Epoch 4/100
654/654 [==============================] - 2s 3ms/step - loss: 0.0438 - accuracy: 1.0000
Epoch 5/100
654/654 [==============================] - 2s 3ms/step - loss: 0.0160 - accuracy: 1.0000
Epoch 6/100
654/654 [==============================] - 1s 2ms/step - loss: 0.0072 - accuracy: 1.0000
Epoch 7/100
654/654 [==============================] - 1s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 8/100
654/654 [==============================] - 2s 2ms/step - loss: 0.0021 - accuracy: 1.0000
Epoch 9/100
654/654 [==============================] - 2s 3ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 10/100
654/654 [==============================] - 2s 3ms/step - loss: 7.8320e-04 - ac

654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 79/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 80/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 81/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 82/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 83/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 84/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 85/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 86/100
654/654 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Epoch 87/100
654/654 [==============================] - 1s 

# Validation

In [14]:
from sklearn.model_selection import train_test_split

x_values = df[["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics"]]

x_train, x_test, y_train, y_test = train_test_split(x_values,y_values,test_size=0.3,random_state=10)

# Check the number of rows in x_train, x_test, y_train and y_test
print("Number of rows in x_train:", x_train.shape[0])
print("Number of rows in x_test:", x_test.shape[0])
print("Number of rows in y_train:", y_train.shape[0])
print("Number of rows in y_test:", y_test.shape[0])

standardise = StandardScaler()

x_train = standardise.fit_transform(x_train)
x_test = standardise.transform(x_test)

Number of rows in x_train: 457
Number of rows in x_test: 197
Number of rows in y_train: 457
Number of rows in y_test: 197


In [15]:
model_val = Sequential()

model_val.add(Dense(6,input_dim=5,activation='relu'))
model_val.add(Dense(6,activation='relu'))
model_val.add(Dense(3,activation='softmax'))

model_val.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

print(model_val.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 36        
                                                                 
 dense_4 (Dense)             (None, 6)                 42        
                                                                 
 dense_5 (Dense)             (None, 3)                 21        
                                                                 
Total params: 99
Trainable params: 99
Non-trainable params: 0
_________________________________________________________________
None


In [16]:
model_val.fit(x_train,y_train,epochs=120,shuffle=True,validation_data=(x_test,y_test), batch_size=1)

Epoch 1/120
457/457 [==============================] - 2s 2ms/step - loss: 1.0667 - accuracy: 0.4004 - val_loss: 0.9973 - val_accuracy: 0.4213
Epoch 2/120
457/457 [==============================] - 1s 2ms/step - loss: 0.9467 - accuracy: 0.4464 - val_loss: 0.8952 - val_accuracy: 0.5127
Epoch 3/120
457/457 [==============================] - 1s 2ms/step - loss: 0.8527 - accuracy: 0.6433 - val_loss: 0.8032 - val_accuracy: 0.6701
Epoch 4/120
457/457 [==============================] - 1s 2ms/step - loss: 0.7398 - accuracy: 0.7396 - val_loss: 0.6883 - val_accuracy: 0.7462
Epoch 5/120
457/457 [==============================] - 1s 2ms/step - loss: 0.6087 - accuracy: 0.7834 - val_loss: 0.5685 - val_accuracy: 0.8325
Epoch 6/120
457/457 [==============================] - 1s 2ms/step - loss: 0.5138 - accuracy: 0.8534 - val_loss: 0.4779 - val_accuracy: 0.8731
Epoch 7/120
457/457 [==============================] - 1s 2ms/step - loss: 0.4454 - accuracy: 0.8862 - val_loss: 0.4220 - val_accuracy: 0.9188

Epoch 58/120
457/457 [==============================] - 1s 3ms/step - loss: 0.1117 - accuracy: 0.9825 - val_loss: 0.0604 - val_accuracy: 0.9848
Epoch 59/120
457/457 [==============================] - 1s 2ms/step - loss: 0.1155 - accuracy: 0.9737 - val_loss: 0.0577 - val_accuracy: 0.9848
Epoch 60/120
457/457 [==============================] - 1s 3ms/step - loss: 0.1129 - accuracy: 0.9781 - val_loss: 0.0531 - val_accuracy: 0.9848
Epoch 61/120
457/457 [==============================] - 1s 2ms/step - loss: 0.1132 - accuracy: 0.9759 - val_loss: 0.0580 - val_accuracy: 0.9797
Epoch 62/120
457/457 [==============================] - 1s 2ms/step - loss: 0.1117 - accuracy: 0.9759 - val_loss: 0.0576 - val_accuracy: 0.9797
Epoch 63/120
457/457 [==============================] - 1s 2ms/step - loss: 0.1143 - accuracy: 0.9825 - val_loss: 0.0510 - val_accuracy: 0.9848
Epoch 64/120
457/457 [==============================] - 1s 2ms/step - loss: 0.1115 - accuracy: 0.9759 - val_loss: 0.0550 - val_accuracy:

Epoch 115/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0966 - accuracy: 0.9803 - val_loss: 0.0487 - val_accuracy: 0.9848
Epoch 116/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0991 - accuracy: 0.9716 - val_loss: 0.0477 - val_accuracy: 0.9848
Epoch 117/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0977 - accuracy: 0.9781 - val_loss: 0.0514 - val_accuracy: 0.9848
Epoch 118/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0969 - accuracy: 0.9781 - val_loss: 0.0526 - val_accuracy: 0.9848
Epoch 119/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0947 - accuracy: 0.9737 - val_loss: 0.0406 - val_accuracy: 0.9898
Epoch 120/120
457/457 [==============================] - 1s 3ms/step - loss: 0.0956 - accuracy: 0.9825 - val_loss: 0.0424 - val_accuracy: 0.9898


In [22]:
df2 = pd.read_csv("Dataset 1 (Iris.data) - Version 2.5.1 (5 columns).csv",header=None)
names = ["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics","Impact"]
df2.columns = names

In [23]:
label_encode = {"Impact": {"High":0, "Moderate":1, "Low":2}}

# Use .replace to change the different classes into numbers
df2.replace(label_encode,inplace=True)

x_val = df2[["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics"]]

In [24]:
x_val_stand = standardise.transform(x_val)

In [25]:
y_val = model_val.predict(x_val_stand)
print(y_val)

[[9.9998522e-01 8.2035015e-08 1.4667148e-05]
 [9.9998534e-01 1.3929871e-07 1.4537501e-05]
 [9.9998534e-01 2.3653219e-07 1.4409039e-05]
 ...
 [6.5905642e-04 9.2999003e-04 9.9841094e-01]
 [2.1383716e-03 4.2739254e-03 9.9358773e-01]
 [7.2374619e-03 7.2654456e-02 9.2010808e-01]]


In [26]:
raw_output = []
for ii in range(0,y_val.shape[0]):
    raw_output.append(np.argmax(y_val[ii,:]))
print(raw_output)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [27]:
mapping = {
    0: 'High',
    1: 'Moderate',
    2: 'Low',
}
final_output = [mapping.get(word, word) for word in raw_output]
print(final_output)

['High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High', 'Low', 'High', 

Validation competed succsesfull !

# Prediction

In [28]:
def prediction(input_data):

    label_encode = {"Impact": {"High":0, "Moderate":1, "Low":2}}
    input_data.replace(label_encode,inplace=True)
    x_new_predict = input_data[["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics"]]
    x_predict = standardise.transform(x_new_predict)
    y_new_predict = model_val.predict(x_predict)
    
    raw_output_pred = []
    raw_output_pred.append(np.argmax(y_new_predict))
    
    mapping = {
            0: 'High',
            1: 'Moderate',
            2: 'Low'}
    
    final_output1 = [mapping.get(num, num) for num in raw_output_pred]
    
    return final_output1

# InterFace


In [29]:
def create_dataFrame(input_list):

    input_dataFrame = pd.DataFrame(columns = ["Metals", "Plastics","Electronics","Hazardous Liquids and Substances","Ceramics"])
    input_dataFrame.loc[len(input_dataFrame)] = input_list
    
    return input_dataFrame

In [30]:
def get_values():
    
    input_list =[]
    
    Metal_Val = float(input("Enter % of Metal in the Product: "))
    input_list.append(Metal_Val)
    
    Plastic_Val = float(input("Enter % of Plastics in the Product: "))
    input_list.append(Plastic_Val)
    
    E_Val = float(input("Enter % of Electronics in the Product: "))
    input_list.append(E_Val)

    H_Val = float(input("Enter % of Hazordous Liquids and Substances in the Product: "))
    input_list.append(H_Val)
    
    Cera_Val = float(input("Enter % of Ceramics in the Product: "))
    input_list.append(Cera_Val)
    
    if sum(input_list) > 100:
        print("Error: Incorrect Values entered (Values excead 100%)")
        
    else:
        return input_list

In [ ]:
print("**********Choose an Option:********* ")
print("0: Use Command Line Interface")
print("1: To exit")

while True :

    choice = int(input("Enter choice:"))



    if choice == 0:
        print(":============-EcoCheck.ai-=============:")
        print("Starting...\n")
        print("===-Product Info-===")
        print("(Enter % Values in scale of 10% = 1)\n")
        
        input_list = get_values()
        
        input_dataFrame = create_dataFrame(input_list)
        output = prediction(input_dataFrame)
                            
        print("\n")
        print("Predicted Environmental Impact is : ", output)
        print("\n")
        
    elif choice == 1:
        print("\nExiting!\n")
        break

    elif choice not in (0,1):
        print("Invalid option")

**********Choose an Option:********* 
0: Use Command Line Interface
1: To exit
Enter choice:0
:============-EcoCheck.ai-=============:
Starting...

===-Product Info-===
(Enter % Values in scale of 10% = 1)

Enter % of Metal in the Product: 100
Enter % of Plastics in the Product: 0
Enter % of Electronics in the Product: 0
Enter % of Hazordous Liquids and Substances in the Product: 0
Enter % of Ceramics in the Product: 0


Predicted Environmental Impact is :  ['High']


